controller_list:
  - name: fake_right_arm_controller
    joints:
      - pan_joint
      - right_arm_tilt_joint
      - right_arm_lift_joint
      - right_arm_rotate_joint
      - right_arm_elbow_joint
      - right_arm_wrist_yaw_joint
      - right_arm_wrist_tilt_joint
  - name: fake_left_arm_controller
    joints:
      - pan_joint
      - left_arm_tilt_joint
      - left_arm_lift_joint
      - left_arm_rotate_joint
      - left_arm_elbow_joint
      - left_arm_wrist_yaw_joint
      - left_arm_wrist_tilt_joint
  - name: fake_right_gripper_controller
    joints:
      - right_arm_gripper_joint
  - name: fake_left_gripper_controller
    joints:
      - left_arm_gripper_joint